# fly.toml - Configuração do Fly.io

app = "chat-lajinha"
primary_region = "gru" # São Paulo, Brasil - Mais próximo!

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Mantém sempre ativo! Importante para WebSocket
  auto_start_machines = true
  min_machines_running = 1 # Sempre 1 máquina rodando

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/api/status"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

